import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CustomRainbowKitProvider from "./CustomRainbowKitProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/shared/Layout";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "ArtDrop App",
  description: "Generated by DCA for Alyra training",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomRainbowKitProvider>
          <Layout>
            {children}
          </Layout>
        </CustomRainbowKitProvider>
      </body>
    </html>
  );
}